name: Functional test
on:
  push:
    #  - main
    #  - master
  workflow_dispatch:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  bootstrap-fedora:
    runs-on: ubuntu-latest
    container:
      image: "fedora:41"
    steps:
      - uses: actions/checkout@v4
        with:
          path: checkout/

      - name: Run tests
        working-directory: checkout/
        run: ./test.sh --skip-checkout

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
